server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: http://localhost:8002/
          predicates:
            - Path=/clients/**
        - id: product-service
          uri: http://localhost:8010/
          predicates:
            - Path=/products/**
