server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clientbd
    username: root
    password: secret.A3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
<<<<<<< HEAD
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
=======
    generate-ddl: true
>>>>>>> c6816c244593f737c9b27a9bd81affe2379bc6e2
