server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clientbd
    username: root
    password: secret.A3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuit breaker:
    instances:
      operation:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true